import { t } from "@lingui/macro";
import { PlayserveResponseError } from "./response";
import { MessageType } from "./message";

export enum ApiError {
  Generic = 0,
  AuthenticationRequired = 1,
  BadRequest = 2,
  AppLaunchError = 3,
  AppDownloadError = 4,
  SetJwtError = 5,
  DriveInfoError = 6,
  WinetricksInstallError = 7,
  WineInstallError = 8,
  RuntimeInstallError = 9,
  AppNotInstalledError = 10,
  AppAlreadyRunningError = 11,
  AnotherAppAlreadyRunningError = 12,
  AppDownloadInProgressError = 13,
  WineError = 15,
  ConfigDoesNotExist = 16,
  LegendaryNotInstalled = 17,
  SteamcmdNotInstalled = 18,
  NoDownloadInProgress = 19,
  AppInstalled = 20,
  ConfigCopyIdNotFound = 21,
  WebviewNotFound = 22,
  EpicAuth = 23,
  InvalidRoute = 24,
  NoAppFoundToUninstall = 25,
  CancelDownloadError = 26,
  AppNotSupportedInOS = 27,
  NoInternet = 28,
  SteamAuth = 29,
  Invalid2fa = 30,
  Timeout = 31,
  SteamGuardTimeout = 32,
  ProtonNotFound = 33,
  SteamClientLaunch = 34,
  SteamClientUpdate = 35,
  AppRunning = 36,
  MissingCreds = 37,
  AppNotOwned = 38,
  AppUpdateNeeded = 39,
  RateLimitExceeded = 40,
  SteamNotFound = 41,
  SteamConfigError = 42,
  SetDeviceIdError = 43,
  WirelessDeviceNotFound = 44,
  AccessPointNotConnected = 45,
  AccessPointNotFound = 46,
  MissingAccessPointPassword = 47,
  MissingNetworkManagerProxy = 48,
  NoWriteAccess = 49,
  MissingTestScriptId = 50,
  TestScriptNotFound = 51,
  MissingAppId = 52,
  SubmissionAlreadySubmitted = 53,
  SteamClientNotInitialized = 54,
  InvalidProvider = 55,
  SteamUpdating = 56,
  GenericDownload = 57,
  FailedToTerminateAutoTest = 58,
  FailedToSubmitTestScript = 59,
  NoSpaceLeft = 60,
  AppNotFound = 61,
  SniperNotFound = 62,
  CurrentUserNotFound = 63,
  ScriptResultMissingRunAt = 64,
  SteamClientInUse = 65,
  ProtonInstallError = 66,
  OrySessionSaveError = 67,
  OrySessionGetError = 68,
  AppMove = 69,
  OsUpdateError = 70,
  AppNotRunning = 71,
  AppLaunchInstalling = 72,
  FailedToDeleteSubmission = 73,
  FailedToDuplicateSubmissionMissingCategory = 74,
  DriveUsageError = 75,
  ProviderCannotDownload = 76,
  ProviderCannotLaunch = 77,
  FailedToSaveSubmission = 78,
  FailedToParseSubmissionItemData = 79,
  FactoryResetError = 80,
  ConnectionFailed = 81,
  SavedConnectionNotFound = 82,
  AccessPointConnectionFailed = 83,
  ReaperNotRunning = 84,
  ReaperAlreadyRunning = 85,
  ScreenshotRequest = 86,
  InstallError = 87,
  CloudSave = 88,
  BluetoothManagerProxyNotInitialized = 89,
  BluetoothDiscoveryStartFailed = 90,
  BluetoothAdapterProxyNotInitialized = 91,
  RunnerVersionNotFound = 92,
  PipewireConnectionFailed = 93,
  PipewireVolumeGet = 94,
  PipewirePluginNotFound = 95,
  PipewireAudioDeviceProfile = 96,
  PipewireDeviceNotFound = 97,
  PipewirePODSerializeFail = 98,
  PipewireDefaultSinkSet = 99,
  NotImplemented = 100,
  GogAuth = 101,
  ProviderCannotGetApps = 102,
  BluetoothConnectFailed = 103,
  SteamCMDSessionReplaced = 104,
  SteamCMDAppUpdateFailed = 105,
  SteamCMDNoOutput = 106,
  AppUninstall = 107,
  SteamCMDError = 108,
  DriveFormatError = 109,
  DriveFormatRoot = 110,
  DrivePerformanceError = 111,
  EulaNotAccepted = 112,
  DownloadErrorWithRetry = 113,
  AppDiskNotFound = 114,
  BadFileDescriptor = 115,
  RootDriveNotFound = 116,
  ToolInstalling = 117,
  ProviderDisabled = 118,
  AppInstalling = 119,
  InvalidProviderSession = 120,
  SubmissionNotFound = 121,
  HttpError = 122,
  DownloadCancelled = 123,
  DependenciesMissing = 124,
  DBError = 125
}

export const getApiErrorTranslation = (
  body: PlayserveResponseError<MessageType>["body"]
) => {
  if (!body) {
    return "";
  }
  // TODO: Translate more errors
  switch (body.error_code) {
    case ApiError.MissingAppId:
      return t`Game is not owned or provider is not authorized`;
    default:
      return body.message;
  }
};
