name: Lint and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Check typescript
        run: pnpm tsc
      - name: Test
        run: pnpm test:ci
  
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Lint
        run: cargo fmt --check
        working-directory: src-tauri
      - name: Clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri
